### ISSUE TITLE
Unsupported locale setting

### ISSUE THREAD

**Issue by vaishnavmhetre** [almostearthling/when-command#89]
**running 'when-command' through terminal with or without root privileges dumps following error statements**

```
mqalpha@MQAlpha:~$ when-command 
Traceback (most recent call last):
  File "/usr/bin/when-command", line 17, in <module>
    "/usr/share/when-command/when-command.py").load_module()
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/share/when-command/when-command.py", line 569, in <module>
    locale.setlocale(locale.LC_ALL, locale.getlocale())
  File "/usr/lib/python3.5/locale.py", line 595, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

```

Need quick solution over it

**Comment by almostearthling** [comment]
I might need some more information, at least to emulate the issue.

1. What are your locale settings? The full output of the `locale` command could be useful for me.
2. What locales are supported in your system? The output of the `locale -a` command.
3. Can you run `when-command` from the command line with different locale settings (for instance by setting the `LANG` variable before starting **When**, as in `export LANG=C when-command`, or by temporarily changing your session language to US english)?
4. Can you please post the output of the command below?

```
python3 -c "import locale; print(locale.getlocale())"
```

Thank you for reporting the issue... This said, I'll work it around anyway by setting a default locale if the current locale is not supported. Consider that there are not so many translations for **When** because it's a rather young project and I'm not good at foreign languages enough to work on translations different from (presumably bad) english and fairly good italian.

**Comment by MorpherQAlpha** [comment]
Thanks but I reconfigured the locale settings using dpkg-reconfigure

**Comment by almostearthling** [comment]
Is it possible, however, to gather the information I asked for above, related to your previous settings?

**Comment by MorpherQAlpha** [comment]
Ughh.! Sorry but I reformatted and replaced my Ubuntu with Kali..! So I
can't provide you the information.

**Comment by almostearthling** [comment]
Ok, I'll deploy the version containing the workaround mentioned above: it'll choose English when localization errors occur.

**Comment by MorpherQAlpha** [comment]
Sure. Thanks for your kind support.
